### ISSUE TITLE
Found a better fixed table header lib

### ISSUE THREAD

**Issue by jesscold** [markmalek/Fixed-Header-Table#105]
Found a lib that doesn't seem to have as many issues as this one:

http://mkoryak.github.io/floatThead/

Many of the open issues of this lib do not exist there. Wanted to pass this on since it saved me some headaches

**Comment by JackWells** [comment]
94 Open Issues now.  Thanks for the link jesscold.  Projects in this state should really be labeled "currently unusuable" on the front page, to save people trying to get work done from spending time trying in vain to make them work.  Putting the header in a separate div with different col-widths and an un-synced scroll bar is not "ready for production" by a stretch.
